### Image Pyramid using OpenCV

In [2]:
import cv2
import numpy as np

In [2]:
# Work with images with default resolution but many times we need to change the resolution (lower it) or resize the original
#  image in that case, image pyramids comes handy

In [27]:
img=cv2.imread("/Users/mehulgupta2409/Documents/Code /AI ML/AI/OpenCV/Image/Face Photo 2379005.jpeg")
# new=cv2.resize(img,(500,500))
print(img.shape)
# Going in to small images
new=cv2.pyrDown(img)
print(new.shape)
# new1=cv2.pyrDown(new)
# print(new1.shape)
# new2=cv2.pyrDown(new1)
# print(new2.shape)
# new3=cv2.pyrDown(new2)
# print(new3.shape)


# cv2.imshow("am",img)
# cv2.imshow("m",new)
# cv2.imshow("mwq",new1)
# cv2.imshow("mwqw",new2)
# cv2.imshow("mwqsw",new3)

# Again going to big images - it will create blur image as we are stretching it further apart
new4=cv2.pyrUp(new)
print(new4.shape)
# new5=cv2.pyrUp(new4)
# print(new5.shape)
# new6=cv2.pyrUp(new5)
# print(new6.shape)
# new7=cv2.pyrUp(new6)
# print(new7.shape)
cv2.imshow("iOOdvv",new4)
# cv2.imshow("iOOd",new5)
# cv2.imshow("iOO",new6)
# cv2.imshow("ce",new7)
cv2.waitKey(25)
cv2.destroyAllWindows()

(625, 500, 3)
(313, 250, 3)
(626, 500, 3)


### Image translation using OpenCV

In [28]:
# Advantages/Application of Image translation are
# 1) Hiding a part of the image
# 2) Croping an image
# 3) Shifting an Image
# 4) Animating an image using image transloations in loop

In [36]:
new_img=cv2.imread("/Users/mehulgupta2409/Documents/Code /AI ML/AI/OpenCV/Image/Face Photo 2379005.jpeg",1)
print(new_img.shape)
# cv2.imshow("s",new_img)
new_img=cv2.resize(new_img,(600,600))
# now we need to make kernel matrix to get our image translate
kernel_matrix=np.float32([[1,0,10],[0,1,100]])
# print(new_img)
# kernel_matrix
new=cv2.warpAffine(new_img,kernel_matrix,(600,600))

cv2.imshow("hedre",new_img)
cv2.imshow("hese",new)
# cv2.imshow("herecec",kernel_matrix)
cv2.waitKey(10)
cv2.destroyAllWindows()

(625, 500, 3)


### Geometric Transformation of Images

In [37]:
# Transformation (about axis x and y)- 1)Scaling
#                  2)Translation
#                  3)Rotation
# Affine Transformation - rotate
# Perspecive Transformation - crop


# 1)Translation
# 2)Euclidean
# 3)Similarity
# 4)Affine
# 5)Projective

### Background Subtraction using OpenCV in Video
<h5>In Image we do Edge detection , nut here in video we do background subtraction method

In [17]:
org_video=cv2.VideoCapture("/Users/mehulgupta2409/Downloads/Videos/Check CCTV Recording.mp4")
sub_background=cv2.createBackgroundSubtractorMOG2()
while org_video.isOpened():
    r,frame=org_video.read()
    if r==False:
        break
    frame=cv2.resize(frame,(700,500))
    sub_v=sub_background.apply(frame)
    cv2.imshow("se",sub_v)
    # cv2.imshow("s",frame)
    if cv2.waitKey(25) & 0xff==ord("p"):
        break

org_video.release()
cv2.destroyAllWindows()

### Extract images from video using OpenCV

In [22]:
cap=cv2.VideoCapture("/Users/mehulgupta2409/Downloads/Videos/Niagara Falls UHD 30fps.mp4")
num=0
while True:
    r,frame=cap.read()
    if r==False :
        break
    frame=cv2.resize(frame,(700,550))
    filename="/Users/mehulgupta2409/Documents/Code /AI ML/AI/OpenCV/Images from Video/image_"+str(num)+".png"
    cv2.imwrite(filename,frame)
    num=num+1
    cv2.imshow("abc",frame)
    if cv2.waitKey(25) & 0xff==ord("p"):
        break
cap.release()
cv2.destroyAllWindows()

### cvtColor method OpenCV

In [34]:
old_img=cv2.imread("/Users/mehulgupta2409/Documents/Code /AI ML/AI/OpenCV/Image/Face Photo 2379005.jpeg")
new_img=cv2.cvtColor(old_img,cv2.COLOR_BGR2RGB)
# cv2.imshow("fface",old_img)
cv2.imshow("face",new_img)
cv2.waitKey(1)
cv2.destroyAllWindows()

### Crop image using OpenCV

In [12]:
old_img=cv2.imread("/Users/mehulgupta2409/Documents/Code /AI ML/AI/OpenCV/Image/Face Photo 2379005.jpeg")
old_img=cv2.resize(old_img,(500,500))
# image[y1:y2,x1:x2] where x1,y1 are the top left points and x2,y2 are the bottom right points
crop_img=old_img[60:400,60:400]

cv2.imshow("faece",old_img)
cv2.imshow("facewe",crop_img)
cv2.waitKey(1)
cv2.destroyAllWindows()

### create Blank Image using OpenCV Python

In [13]:
# we need a numpy array for this

In [48]:
# new_img=np.ones((2,5,3))
new_img=np.ones((500,500,1),np.uint8)*168
# new_img=np.ones((500,500,3),np.uint8)*100
print(new_img)
cv2.imshow("s",new_img)
cv2.waitKey(1)
cv2.destroyAllWindows()

[[[168]
  [168]
  [168]
  ...
  [168]
  [168]
  [168]]

 [[168]
  [168]
  [168]
  ...
  [168]
  [168]
  [168]]

 [[168]
  [168]
  [168]
  ...
  [168]
  [168]
  [168]]

 ...

 [[168]
  [168]
  [168]
  ...
  [168]
  [168]
  [168]]

 [[168]
  [168]
  [168]
  ...
  [168]
  [168]
  [168]]

 [[168]
  [168]
  [168]
  ...
  [168]
  [168]
  [168]]]


### Color picker using OpenCV Python

In [52]:
def fun(x):
    pass

In [58]:

img=np.ones((3,600,600),np.uint8)*0
# img=cv2.resize(img,(600,500))
cv2.namedWindow("reakk")

cv2.createTrackbar("R","reakk",0,255,fun)
cv2.createTrackbar("G","reakk",0,255,fun)
cv2.createTrackbar("B","reakk",0,255,fun)

while True:
    cv2.imshow("reakk",img)
    if cv2.waitKey(20) & 0xff==ord("p"):
        break
    r=cv2.getTrackbarPos("R","reakk")
    g=cv2.getTrackbarPos("G","reakk")
    b=cv2.getTrackbarPos("B","reakk")
    img[:]=[b,g,r]

cv2.destroyAllWindows()

error: OpenCV(4.10.0) /Users/xperience/GHA-Actions-OpenCV/_work/opencv-python/opencv-python/opencv/modules/core/src/matrix_c.cpp:190: error: (-5:Bad argument) Unknown array type in function 'cvarrToMat'
